spring: 
  application: 
    name: veiculos
  datasource:
    url: jdbc:h2:mem:veiculos 
    username: sa 
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled:  true
      path: /h2-console

